services:
  postgres:
    image: postgres:17-bookworm
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=llm_summarize
  summarizer:
    restart: always
    build:
      dockerfile: Dockerfile
    env_file:
      - local_dev.env